/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : Status,
  'specialRequests' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'partyDate' : IDL.Text,
  'phone' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
  'packageId' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
  'maxGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Booking],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'init' : IDL.Func([], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Text, Status], [Booking], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : Status,
    'specialRequests' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'partyDate' : IDL.Text,
    'phone' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
    'packageId' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
    'maxGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Booking],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'init' : IDL.Func([], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Text, Status], [Booking], []),
  });
};

export const init = ({ IDL }) => { return []; };