/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'customerName' : string,
  'status' : Status,
  'specialRequests' : string,
  'createdAt' : bigint,
  'email' : string,
  'partyDate' : string,
  'phone' : string,
  'numberOfGuests' : bigint,
  'packageId' : string,
}
export interface Package {
  'id' : string,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'maxGuests' : bigint,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface _SERVICE {
  'createBooking' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    Booking
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getBookingsByEmail' : ActorMethod<[string], Array<Booking>>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'init' : ActorMethod<[], undefined>,
  'updateBookingStatus' : ActorMethod<[string, Status], Booking>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];